name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
        env:
          VITE_FIREBASE_API_KEY: dummy
          VITE_FIREBASE_AUTH_DOMAIN: dummy
          VITE_FIREBASE_PROJECT_ID: gen-lang-client-0157482863
          VITE_FIREBASE_STORAGE_BUCKET: gen-lang-client-0157482863.appspot.com
          # leave AI key empty; build should still succeed
