name: Build & Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  NODE_VERSION: '20'
  # Prevents some tools from turning warnings into failures
  CI: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (Vite -> dist/)
        run: npm run build

      - name: Verify build output exists
        run: |
          test -f dist/index.html || (echo "dist/index.html missing" && exit 1)
          test -d dist/assets || (echo "dist/assets/ missing" && exit 1)
          echo "Build looks good ✔"

      # Deploy using Firebase official action
      - name: Deploy to Firebase Hosting (gen-lang-client-0157482863)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: gen-lang-client-0157482863
          channelId: live
