name: Build, Release & Deploy

on:
  push:
    branches: [ "main", "stable-*" ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm ci

      - name: Build
        env:
          # Provide at build time if your app expects it during `vite build`
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
        run: npm run build --if-present

      - name: Archive dist
        if: ${{ hashFiles('dist/**') != '' }}
        run: |
          mkdir -p artifacts
          ( [ -d dist ] && cd dist && zip -qry ../artifacts/app-dist.zip . ) || echo "no dist/ to zip"

      - name: Upload artifact
        if: ${{ hashFiles('artifacts/app-dist.zip') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: artifacts/app-dist.zip

  release:
    # Create a GitHub Release when a tag v* is pushed (e.g., npm run release)
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: artifacts/app-dist.zip

  deploy:
    # Deploy to Firebase Hosting when pushing to main or stable-*
    needs: build
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/heads/main') ||
      startsWith(github.ref, 'refs/heads/stable-')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm ci

      - name: Build
        env:
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
        run: npm run build --if-present

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase use gen-lang-client-0157482863
          # If you only host the SPA, keep --only hosting. Add more targets if needed.
          firebase deploy --only hosting
